### ISSUE TITLE
For anyone facing the error : Multiple anonymous defines encountered

### ISSUE THREAD

**Issue by NotSqrt** [cujojs/curl#283]
My pages have been facing "Multiple anonymous defines encountered" irregularly for some time, and I have finally understood why :

I have set up a minimalistic page to demonstrate the error : http://jsbin.com/suhehuwita/1/
This page triggers the error very reliably, but in a real world web page with more modules, it would happen randomly.

Basically, if an AMD-compatible module is loaded after curl, outside a call to curl(), the error will be triggered.

What you should not do:
```html
<html>
	<head>
		<script type="text/javascript">
			curl = {/* curl config */};
		</script>
		<script src="/curl.js"></script>
		<script src="/some-amd-module.js"></script> <!-- after curl -->
	</head>
	<body>
		<script type="text/javascript">
			curl("same-amd-module", function () {});
		</script>
	</body>
</html>
```
What you should do instead:
```html
<html>
	<head>
		<script type="text/javascript">
			curl = {/* curl config */};
		</script>
		<script src="/some-amd-module.js"></script> <!-- before curl -->
		<script src="/curl.js"></script>
	</head>
	<body>
		<script type="text/javascript">
			curl("same-amd-module", function () {});
		</script>
	</body>
</html>
```

**Comment by unscriptable** [comment]
Thanks @NotSqrt!  This is a common problem encountered by people mixing AMD loaders and `<script>` elements that might load AMD modules.  I'm glad you figured it out and left a solution for others! -- J
