### ISSUE TITLE
Remove old IE event listeners in domReady

### ISSUE THREAD

**Issue by ravager** [cujojs/curl#285]
https://github.com/cujojs/curl/blob/master/src/curl/domReady.js#L104-L105

The first parameter to both `attachEvent` and `detachEvent` should match.  Currently, the attached listeners are not being detached for old IEs.

Also, perhaps `attachEvent` should be inspected before assuming it can be used in that "else" block.

Possible fix:
```javascript
else if ('attachEvent' in global) {
	addEvent = function (node, event) {
		event = 'on' + event;
		node.attachEvent(event, checkDOMReady);
		return function () { node.detachEvent(event, checkDOMReady); };
	};
}
```

But then should there be a final "else", or should `addEvent` be defined as a no-op by default?

**Comment by unscriptable** [comment]
Thanks @ravager!  Silly DOM events are so silent.  

> else if ('attachEvent' in global)

Yah, this is a probably a good idea.  However, early on, we decided to use the assume-MS-if-not-W3C pattern, instead.  I just fixed the event name (similar to what you proposed) so it is consistent the the rest of the code.
