### ISSUE TITLE
License for curl

### ISSUE THREAD

**Issue by alhume** [cujojs/curl#287]
Hello, which license is curl licensed under?  MIT?  Apache?  Any help would be appreciated as cannot find any reference to it so far.

**Comment by scothis** [comment]
Are these insufficient?
https://github.com/cujojs/curl/blob/master/package.json#L6
https://github.com/cujojs/curl/blob/master/LICENSE.txt

**Comment by alhume** [comment]
Ah thank you!  Right so they just license under the Github terms and not a separate license?

**Comment by scothis** [comment]
Both of those links are specific to curl.js, they just happen to be hosted from github. curl.js is MIT licensed.

**Comment by alhume** [comment]
Thank you very much!  I thought it might be but just could not find a reference to MIT on any of the pages.  Thanks again - appreciate your quick response :)
