### ISSUE TITLE
"new Promise()" syntax non-standard?

### ISSUE THREAD

**Issue by michielbdejong** [cujojs/curl#291]
If you run `new Promise()` in Firefox 41, you get an error:
````
TypeError: Not enough arguments to Promise.
````
This means that [dist/debug/curl.js#L300](https://github.com/cujojs/curl/blob/c7d937faa53599fbc06e31c0fc248b9fcf0ea899/dist/debug/curl.js#L300) will fail when used as-such in a browser environment.

Should this be changed to the more standard `new Promise(function(resolve, reject) {})` syntax? Or is `dist/debug/curl.js` not meant for use in a browser environment?

**Comment by unscriptable** [comment]
See #294.
